workflows:
  android-workflow:
    name: Codemagic Android Workflow
    max_build_duration: 15
    instance_type: mac_mini_m2
    environment:
      android_signing:
        - keystore_android_reference
      vars:
        PACKAGE_NAME: "io.enactus.duniya.reactnative"
    scripts:
      - name: Set Android SDK location
        script: |
          echo "sdk.dir=$ANDROID_SDK_ROOT" > "$CM_BUILD_DIR/android/local.properties"
      - name: Install npm dependencies
        script: |
          npm install
      - name: Run Expo Prebuild
        script: |
          npx expo prebuild
      - name: Set up app/build.gradle
        script: |
          mv ./support-files/build.gradle android/app
      - name: Build Android release
        script: |
          cd android
          chmod +x ./gradlew
          ./gradlew assembleRelease
    artifacts:
      - android/app/build/outputs/**/*.apk
    publishing:
      email:
        recipients:
          - sunnywongs523@gmail.com
          - shahanahsyed@gmail.com
          - 101463656@georgebrown.ca
          - hans.casilao@gmail.com
        notify:
          success: true
          failure: true

  ios-workflow:
    name: iOS Sample Workflow
    environment:
      vars:
        BUNDLE_ID: "io.enactus.duniya.reactnative"
        XCODE_WORKSPACE: "EnactusDuniya.xcworkspace"
        XCODE_SCHEME: "EnactusDuniya"
    scripts:
      - name: Install npm dependencies
        script: |
          npm install
      - name: Run Expo Prebuild
        script: |
          npx expo prebuild -p ios
      - name: Set Info.plist values
        script: |
          PLIST=$CM_BUILD_DIR/$XCODE_SCHEME/Info.plist
          PLIST_BUDDY=/usr/libexec/PlistBuddy
          $PLIST_BUDDY -c "Add :ITSAppUsesNonExemptEncryption bool false" $PLIST
      - name: Install CocoaPods dependencies
        script: |
          cd ios && pod install
      - name: Build ipa for distribution
        script: |
          xcode-project build-ipa \
            --workspace "$CM_BUILD_DIR/ios/$XCODE_WORKSPACE" \
            --scheme "$XCODE_SCHEME"
    artifacts:
      - build/ios/ipa/*.ipa
      - /tmp/xcodebuild_logs/*.log
      - $HOME/Library/Developer/Xcode/DerivedData/**/Build/**/*.app
      - $HOME/Library/Developer/Xcode/DerivedData/**/Build/**/*.dSYM
