workflows:
  android-workflow:
    name: Codemagic Android Workflow
    max_build_duration: 15
    instance_type: mac_mini_m2
    environment:
      android_signing:
        - keystore_android_reference
      vars:
        PACKAGE_NAME: "io.enactus.duniya.reactnative"
    scripts:
      - name: Install dependencies and Expo CLI, and eject app
        script: |
          npm install
          npm install -g expo-cli
          expo eject --non-interactive
      - name: Set up app/build.gradle
        script: |
          mv ./support-files/build.gradle android/app
      - name: Set Android SDK location
        script: |
          echo "sdk.dir=$ANDROID_SDK_ROOT" > "$CM_BUILD_DIR/android/local.properties"
      - name: Build Android release
        script: |
          cd android
          ./gradlew bundleRelease
    artifacts:
      - android/app/build/outputs/**/*.aab
    publishing:
      email:
        recipients:
          - sunnywongs523@gmail.com
        notify:
          success: true
          failure: true
